-- SQLINES DEMO *** le SQL Developer Data Modeler 24.3.1.351.0831
-- SQLINES DEMO *** -02-09 19:15:57 CET
-- SQLINES DEMO *** le Database 11g
-- SQLINES DEMO *** le Database 11g



-- SQLINES DEMO *** no DDL - MDSYS.SDO_GEOMETRY

-- SQLINES DEMO *** no DDL - XMLTYPE

-- SQLINES FOR EVALUATION USE ONLY (14 DAYS)
CREATE TABLE Autor 
    ( 
     usrnm VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Autor 
    ADD CONSTRAINT Autor_PK PRIMARY KEY ( usrnm ) ;

CREATE TABLE Citalac 
    ( 
     usrnm VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Citalac 
    ADD CONSTRAINT Citalac_PK PRIMARY KEY ( usrnm ) ;

CREATE TABLE Deo 
    ( 
     id_deo        INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     nas_deo       VARCHAR (4000) , 
     ind_deo       INTEGER , 
     dat_deo       TIMESTAMP(0) , 
     Strip_sfr_str INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Deo 
    ADD CONSTRAINT Deo_PK PRIMARY KEY ( id_deo, Strip_sfr_str ) ;

CREATE TABLE izdaje 
    ( 
     Serijal_sfr_srj        INTEGER  NOT NULL , 
     Izdavacka_kuca_sfr_izd INTEGER  NOT NULL 
    ) 
;

ALTER TABLE izdaje 
    ADD CONSTRAINT izdaje_PK PRIMARY KEY ( Serijal_sfr_srj, Izdavacka_kuca_sfr_izd ) ;

CREATE TABLE Izdavacka_kuca 
    ( 
     sfr_izd INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     naz_izd VARCHAR (4000)  NOT NULL , 
     lnk_izd VARCHAR (4000) 
    ) 
;

ALTER TABLE Izdavacka_kuca 
    ADD CONSTRAINT Izdavacka_kuca_PK PRIMARY KEY ( sfr_izd ) ;

CREATE TABLE je_dostupan_na 
    ( 
     Serijal_sfr_srj INTEGER  NOT NULL , 
     Servis_sfr_ser  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE je_dostupan_na 
    ADD CONSTRAINT je_dostupan_na_PK PRIMARY KEY ( Serijal_sfr_srj, Servis_sfr_ser ) ;

CREATE TABLE je_procitao 
    ( 
     Citalac_usrnm  VARCHAR (4000)  NOT NULL , 
     Deo_id_deo     INTEGER  NOT NULL , 
     Deo_sfr_str    INTEGER  NOT NULL , 
     je_procitao_ID INTEGER NOT NULL 
    ) 
;

ALTER TABLE je_procitao 
    ADD CONSTRAINT je_procitao_PK PRIMARY KEY ( je_procitao_ID ) ;

CREATE TABLE je_stila 
    ( 
     Umetnicki_stil_id_stil INTEGER  NOT NULL , 
     Strip_sfr_str          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE je_stila 
    ADD CONSTRAINT je_stila_PK PRIMARY KEY ( Umetnicki_stil_id_stil, Strip_sfr_str ) ;

CREATE TABLE je_zanra 
    ( 
     Zanr_id_zanr    INTEGER  NOT NULL , 
     Serijal_sfr_srj INTEGER  NOT NULL 
    ) 
;

ALTER TABLE je_zanra 
    ADD CONSTRAINT je_zanra_PK PRIMARY KEY ( Zanr_id_zanr, Serijal_sfr_srj ) ;

CREATE TABLE Kategorija 
    ( 
     id_kat        INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     naz_kat       VARCHAR (4000)  NOT NULL , 
     Citalac_usrnm VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Kategorija 
    ADD CONSTRAINT Kategorija_PK PRIMARY KEY ( id_kat, Citalac_usrnm ) ;

CREATE TABLE Korisnik 
    ( 
     usrnm     VARCHAR (4000)  NOT NULL , 
     sfr       VARCHAR (4000)  NOT NULL , 
     dat_log   TIMESTAMP , 
     email     VARCHAR (4000)  NOT NULL , 
     prof_ime  VARCHAR (4000)  NOT NULL , 
     uloga_kor VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Korisnik 
    ADD CONSTRAINT CH_INH_Korisnik 
    CHECK (uloga_kor IN ('Autor', 'Citalac', 'Korisnik')) 
;

ALTER TABLE Korisnik 
    ADD CONSTRAINT Korisnik_PK PRIMARY KEY ( usrnm ) ;

CREATE TABLE prati 
    ( 
     Korisnik_usrnm  VARCHAR (4000)  NOT NULL , 
     Korisnik_usrnm1 VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE prati 
    ADD CONSTRAINT prati_PK PRIMARY KEY ( Korisnik_usrnm, Korisnik_usrnm1 ) ;

CREATE TABLE pripada 
    ( 
     Strip_sfr_str   INTEGER  NOT NULL , 
     Serijal_sfr_srj INTEGER  NOT NULL 
    ) 
;

ALTER TABLE pripada 
    ADD CONSTRAINT pripada_PK PRIMARY KEY ( Strip_sfr_str, Serijal_sfr_srj ) ;

CREATE TABLE radi_na 
    ( 
     Strip_sfr_str INTEGER , 
     Deo_id_deo    INTEGER  NOT NULL , 
     Deo_sfr_str   INTEGER  NOT NULL , 
     Autor_usrnm   VARCHAR (4000)  NOT NULL , 
     uloga_autor   VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE radi_na 
    ADD 
    CHECK (uloga_autor IN ('pisac', 'pomocnik', 'umetnik')) 
;

CREATE TABLE Recenzija 
    ( 
     id_rec                     INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     ocn_rec                    INTEGER , 
     dat_rec                    TIMESTAMP , 
     kom_rec                    VARCHAR (4000) , 
     je_procitao_je_procitao_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Recenzija 
    ADD 
    CHECK (ocn_rec BETWEEN 1 AND 5 OR ocn_rec IN (1, 2, 3, 4, 5)) 
;
CREATE UNIQUE INDEX Recenzija__IDX ON Recenzija 
    ( 
     je_procitao_je_procitao_ID ASC 
    ) 
;

ALTER TABLE Recenzija 
    ADD CONSTRAINT Recenzija_PK PRIMARY KEY ( id_rec ) ;

CREATE TABLE sadrzi 
    ( 
     Kategorija_id_kat        INTEGER  NOT NULL , 
     Kategorija_Citalac_usrnm VARCHAR (4000)  NOT NULL , 
     Strip_sfr_str            INTEGER  NOT NULL 
    ) 
;

ALTER TABLE sadrzi 
    ADD CONSTRAINT sadrzi_PK PRIMARY KEY ( Kategorija_id_kat, Kategorija_Citalac_usrnm, Strip_sfr_str ) ;

CREATE TABLE Serijal 
    ( 
     sfr_srj INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     nas_srj VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Serijal 
    ADD CONSTRAINT Serijal_PK PRIMARY KEY ( sfr_srj ) ;

CREATE TABLE Servis 
    ( 
     sfr_ser INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     naz_ser VARCHAR (4000)  NOT NULL , 
     lnk_ser VARCHAR (4000) 
    ) 
;

ALTER TABLE Servis 
    ADD CONSTRAINT Servis_PK PRIMARY KEY ( sfr_ser ) ;

CREATE TABLE Strip 
    ( 
     sfr_str                 INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     nas_str                 VARCHAR (4000)  NOT NULL , 
     dat_poc                 TIMESTAMP(0) , 
     dat_zav                 TIMESTAMP(0) , 
     Vrsta_izdanja_id_vr_izd INTEGER 
    ) 
;

ALTER TABLE Strip 
    ADD CONSTRAINT Strip_PK PRIMARY KEY ( sfr_str ) ;

CREATE TABLE Umetnicki_stil 
    ( 
     id_stil  INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     naz_stil VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Umetnicki_stil 
    ADD CONSTRAINT Umetnicki_stil_PK PRIMARY KEY ( id_stil ) ;

CREATE TABLE Vrsta_izdanja 
    ( 
     id_vr_izd  INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     naz_vr_izd VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Vrsta_izdanja 
    ADD CONSTRAINT Vrsta_izdanja_PK PRIMARY KEY ( id_vr_izd ) ;

CREATE TABLE Zanr 
    ( 
     id_zanr  INTEGER  GENERATED BY DEFAULT AS IDENTITY ,
     naz_zanr VARCHAR (4000)  NOT NULL 
    ) 
;

ALTER TABLE Zanr 
    ADD CONSTRAINT Zanr_PK PRIMARY KEY ( id_zanr ) ;

ALTER TABLE Autor 
    ADD CONSTRAINT Autor_Korisnik_FK FOREIGN KEY 
    ( 
     usrnm
    ) 
    REFERENCES Korisnik 
    ( 
     usrnm
    ) 
;

ALTER TABLE Citalac 
    ADD CONSTRAINT Citalac_Korisnik_FK FOREIGN KEY 
    ( 
     usrnm
    ) 
    REFERENCES Korisnik 
    ( 
     usrnm
    ) 
;

ALTER TABLE Deo 
    ADD CONSTRAINT Deo_Strip_FK FOREIGN KEY 
    ( 
     Strip_sfr_str
    ) 
    REFERENCES Strip 
    ( 
     sfr_str
    ) 
;

ALTER TABLE izdaje 
    ADD CONSTRAINT izdaje_Izdavacka_kuca_FK FOREIGN KEY 
    ( 
     Izdavacka_kuca_sfr_izd
    ) 
    REFERENCES Izdavacka_kuca 
    ( 
     sfr_izd
    ) 
;

ALTER TABLE izdaje 
    ADD CONSTRAINT izdaje_Serijal_FK FOREIGN KEY 
    ( 
     Serijal_sfr_srj
    ) 
    REFERENCES Serijal 
    ( 
     sfr_srj
    ) 
;

ALTER TABLE je_dostupan_na 
    ADD CONSTRAINT je_dostupan_na_Serijal_FK FOREIGN KEY 
    ( 
     Serijal_sfr_srj
    ) 
    REFERENCES Serijal 
    ( 
     sfr_srj
    ) 
;

ALTER TABLE je_dostupan_na 
    ADD CONSTRAINT je_dostupan_na_Servis_FK FOREIGN KEY 
    ( 
     Servis_sfr_ser
    ) 
    REFERENCES Servis 
    ( 
     sfr_ser
    ) 
;

ALTER TABLE je_procitao 
    ADD CONSTRAINT je_procitao_Citalac_FK FOREIGN KEY 
    ( 
     Citalac_usrnm
    ) 
    REFERENCES Citalac 
    ( 
     usrnm
    ) 
;

ALTER TABLE je_procitao 
    ADD CONSTRAINT je_procitao_Deo_FK FOREIGN KEY 
    ( 
     Deo_id_deo,
     Deo_sfr_str
    ) 
    REFERENCES Deo 
    ( 
     id_deo,
     Strip_sfr_str
    ) 
;

ALTER TABLE je_stila 
    ADD CONSTRAINT je_stila_Strip_FK FOREIGN KEY 
    ( 
     Strip_sfr_str
    ) 
    REFERENCES Strip 
    ( 
     sfr_str
    ) 
;

ALTER TABLE je_stila 
    ADD CONSTRAINT je_stila_Umetnicki_stil_FK FOREIGN KEY 
    ( 
     Umetnicki_stil_id_stil
    ) 
    REFERENCES Umetnicki_stil 
    ( 
     id_stil
    ) 
;

ALTER TABLE je_zanra 
    ADD CONSTRAINT je_zanra_Serijal_FK FOREIGN KEY 
    ( 
     Serijal_sfr_srj
    ) 
    REFERENCES Serijal 
    ( 
     sfr_srj
    ) 
;

ALTER TABLE je_zanra 
    ADD CONSTRAINT je_zanra_Zanr_FK FOREIGN KEY 
    ( 
     Zanr_id_zanr
    ) 
    REFERENCES Zanr 
    ( 
     id_zanr
    ) 
;

ALTER TABLE Kategorija 
    ADD CONSTRAINT Kategorija_Citalac_FK FOREIGN KEY 
    ( 
     Citalac_usrnm
    ) 
    REFERENCES Citalac 
    ( 
     usrnm
    ) 
;

ALTER TABLE prati 
    ADD CONSTRAINT prati_Korisnik_FK FOREIGN KEY 
    ( 
     Korisnik_usrnm
    ) 
    REFERENCES Korisnik 
    ( 
     usrnm
    ) 
;

ALTER TABLE prati 
    ADD CONSTRAINT prati_Korisnik_FKv1 FOREIGN KEY 
    ( 
     Korisnik_usrnm1
    ) 
    REFERENCES Korisnik 
    ( 
     usrnm
    ) 
;

ALTER TABLE pripada 
    ADD CONSTRAINT pripada_Serijal_FK FOREIGN KEY 
    ( 
     Serijal_sfr_srj
    ) 
    REFERENCES Serijal 
    ( 
     sfr_srj
    ) 
;

ALTER TABLE pripada 
    ADD CONSTRAINT pripada_Strip_FK FOREIGN KEY 
    ( 
     Strip_sfr_str
    ) 
    REFERENCES Strip 
    ( 
     sfr_str
    ) 
;

ALTER TABLE radi_na 
    ADD CONSTRAINT radi_na_Autor_FK FOREIGN KEY 
    ( 
     Autor_usrnm
    ) 
    REFERENCES Autor 
    ( 
     usrnm
    ) 
;

ALTER TABLE radi_na 
    ADD CONSTRAINT radi_na_Deo_FK FOREIGN KEY 
    ( 
     Deo_id_deo,
     Deo_sfr_str
    ) 
    REFERENCES Deo 
    ( 
     id_deo,
     Strip_sfr_str
    ) 
;

ALTER TABLE radi_na 
    ADD CONSTRAINT radi_na_Strip_FK FOREIGN KEY 
    ( 
     Strip_sfr_str
    ) 
    REFERENCES Strip 
    ( 
     sfr_str
    ) 
;

ALTER TABLE Recenzija 
    ADD CONSTRAINT Recenzija_je_procitao_FK FOREIGN KEY 
    ( 
     je_procitao_je_procitao_ID
    ) 
    REFERENCES je_procitao 
    ( 
     je_procitao_ID
    ) 
;

ALTER TABLE sadrzi 
    ADD CONSTRAINT sadrzi_Kategorija_FK FOREIGN KEY 
    ( 
     Kategorija_id_kat,
     Kategorija_Citalac_usrnm
    ) 
    REFERENCES Kategorija 
    ( 
     id_kat,
     Citalac_usrnm
    ) 
;

ALTER TABLE sadrzi 
    ADD CONSTRAINT sadrzi_Strip_FK FOREIGN KEY 
    ( 
     Strip_sfr_str
    ) 
    REFERENCES Strip 
    ( 
     sfr_str
    ) 
;

ALTER TABLE Strip 
    ADD CONSTRAINT Strip_Vrsta_izdanja_FK FOREIGN KEY 
    ( 
     Vrsta_izdanja_id_vr_izd
    ) 
    REFERENCES Vrsta_izdanja 
    ( 
     id_vr_izd
    ) 
;

CREATE OR REPLACE FUNCTION ARC_FKArc_1_Citalac_func() RETURNS TRIGGER AS $$  
DECLARE 
    d VARCHAR (4000); 
BEGIN 
    SELECT A.uloga_kor INTO d 
    FROM Korisnik A 
    WHERE A.usrnm = new.usrnm; 
    IF (d IS NULL OR d <> 'Citalac') THEN 
        raise exception '%s', 'FK Citalac_Korisnik_FK in Table Citalac violates Arc constraint on Table Korisnik - discriminator column uloga_kor doesn''t have value ''Citalac''' using errcode = -20223; 
    END IF;

    RETURN NEW;
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 

$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Citalac 
BEFORE INSERT OR UPDATE OF usrnm 
ON Citalac 
FOR EACH ROW
EXECUTE FUNCTION ARC_FKArc_1_Citalac_func();

CREATE OR REPLACE FUNCTION ARC_FKArc_1_Autor_func() RETURNS TRIGGER AS $$  
DECLARE 
    d VARCHAR (4000); 
BEGIN 
    SELECT A.uloga_kor INTO d 
    FROM Korisnik A 
    WHERE A.usrnm = new.usrnm; 
    IF (d IS NULL OR d <> 'Autor') THEN 
        raise exception '%s', 'FK Autor_Korisnik_FK in Table Autor violates Arc constraint on Table Korisnik - discriminator column uloga_kor doesn''t have value ''Autor''' using errcode = -20223; 
    END IF;
    RETURN NEW;
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 

$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Autor 
BEFORE INSERT OR UPDATE OF usrnm 
ON Autor 
FOR EACH ROW
EXECUTE FUNCTION ARC_FKArc_1_Autor_func();

CREATE SEQUENCE je_procitao_je_procitao_ID_SEQ 
START WITH 1 
    CACHE 1 
    /* ORDER */ ;

CREATE OR REPLACE FUNCTION je_procitao_je_procitao_ID_TRG_func() RETURNS TRIGGER AS $$  
BEGIN 
    NEW.je_procitao_ID := je_procitao_je_procitao_ID_SEQ.NEXTVAL; 
END;

$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER je_procitao_je_procitao_ID_TRG 
BEFORE INSERT ON je_procitao 
FOR EACH ROW 
WHEN (NEW.je_procitao_ID IS NULL)
EXECUTE FUNCTION je_procitao_je_procitao_ID_TRG_func();



-- SQLINES DEMO *** per Data Modeler Summary Report: 
-- 
-- SQLINES DEMO ***                        22
-- SQLINES DEMO ***                         1
-- SQLINES DEMO ***                        49
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO *** DY                      0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         3
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***  TYPE                   0
-- SQLINES DEMO ***  TYPE                   0
-- SQLINES DEMO ***  TYPE BODY              0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO *** EGMENT                  0
-- SQLINES DEMO ***                         1
-- SQLINES DEMO *** ED VIEW                 0
-- SQLINES DEMO *** ED VIEW LOG             0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- 
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
-- 
-- SQLINES DEMO ***                         0
-- 
-- SQLINES DEMO ***                         0
-- SQLINES DEMO *** A                       0
-- SQLINES DEMO *** T                       0
-- 
-- SQLINES DEMO ***                         0
-- SQLINES DEMO ***                         0
